app/__init__.py
from flask import Config, Flask


def create_app(config: Config) -> Flask:
    app = Flask(__name__)
    app.config.from_object(config)

    from ._handle_errors import app_handle_errors
    app = app_handle_errors(app)

    from ._url_trailing_slash import app_url_trailing_slash
    app = app_url_trailing_slash(app)

    from .controllers import bp as controllers
    app.register_blueprint(controllers)

    return app

app/controllers.py
from flask import abort, Blueprint, redirect, render_template, Response, url_for
from functools import lru_cache

from .repositories import ArticleRepo
from .utils import slug_regex

bp = Blueprint('controllers', __name__)


@bp.route("/")
@lru_cache()
def home() -> Response:
    return redirect(url_for('controllers.blog_index'))


@bp.route("/about")
@lru_cache()
def about() -> Response:
    return render_template('about.html')


@bp.route("/contact")
@lru_cache()
def contact() -> Response:
    return render_template('contact.html')


@bp.route("/blog")
@lru_cache()
def blog_index() -> Response:
    articles = ArticleRepo.all()
    return render_template('blog_index.html', articles=articles)


@bp.route("/blog/<string:slug>")
@lru_cache()
def blog_article(slug: str) -> Response:
    if not slug_regex.match(slug):
        return abort(400)
    basename = '{}.md'.format(slug)
    article = ArticleRepo.get(basename)
    if not article:
        return abort(404)
    return render_template('base.html', **article._asdict())

app/routes.py
import os
from typing import Dict

from flask import abort, redirect, render_template, url_for

from . import app
from .utils import slug_regex
from .utils.markdown import read_markdown_file


@app.route("/")
def home():
    return redirect(url_for('blog_index'))


@app.route("/about")
def about():
    return render_template('about.html')


@app.route("/contact")
def contact():
    return render_template('contact.html')


@app.route("/blog")
def blog_index():
    articles_path = os.path.join(app.config['ARTICLES_DIR'])
    basenames_unsorted = os.listdir(articles_path)
    basenames = sorted(basenames_unsorted, reverse=True)
    articles = [_article_meta(basename) for basename in basenames]
    return render_template('blog_index.html', articles=articles)


def _article_meta(basename: str) -> Dict[str, str]:
    """Return meta information about the article identified by `basename`."""
    path = os.path.join(app.config['ARTICLES_DIR'], basename)
    _, meta = read_markdown_file(path)
    slug = os.path.splitext(basename)[0]
    return {
        'title': meta.get('title'),
        'url': '/blog/{}'.format(slug)
    }


@app.route("/blog/<string:article>")
def blog_article(article: str):
    if not slug_regex.match(article):
        abort(400)
    try:
        path = os.path.join(app.config['ARTICLES_DIR'], article + '.md')
        html, meta = read_markdown_file(path)
        return render_template('base.html', body=html, **meta)
    except FileNotFoundError:
        abort(404)

app/utils/__init__.py
from typing import List, Optional, TypeVar

import re

slug_regex = re.compile(r'^[a-zA-Z0-9-]{1,64}$')

T = TypeVar('T')


def list_without_nones(lst: List[Optional[T]]) -> List[T]:
    """Return a list without any None values."""
    return [i for i in lst if i is not None]

app/templates/about.html
{% extends "base.html" %}

{% set is_nav_about_active = True %}

{% set title = 'About' %}

{% block content %}
    <p>Hey, I&apos;m Roman.</p>
    <p>I&apos;m a Full-Stack Web Developer <em>(specializing in Back-End &mdash; Python, Scala)</em>.</p>
    <p>A little bit about me:</p>
    <dl class="dl-horizontal">
        <dt>Hobbies:</dt>
        <dd>History, Photography, Cycling, Soccer, Basketball</dd>
        <dt>Languages:</dt>
        <dd>English, Russian <em>(Native)</em></dd>
        <dd>Polish, German <em>(Basic)</em></dd>
    </dl>
    <p>
        My professional accomplishments are detailed in
        <a href="{{ url_for('static', filename='RomanVorobyovResume.pdf') }}" target="_blank">my resume</a>.
    </p>
    <p>
        You can find me on:
        <a href="https://linkedin.com/in/romanvorobyov" target="_blank">LinkedIn</a>,
        <a href="https://github.com/ravoro" target="_blank">GitHub</a>
    </p>
{% endblock %}

app/templates/articles/20170818-memoization-in-python-hello-lru-cache.html
{% extends "blog_article.html" %}

{% block article_title %}Memoization (and Python's lru_cache){% endblock %}

{% block article_body %}
    <header id="article-header">
        <p>
            This article is a brief on memoization and how it can be achieved using Python's
            <a href="https://docs.python.org/3/library/functools.html#functools.lru_cache" target="_blank">
                lru_cache
            </a>
            decorator.
        </p>
    </header>

    <p>
        Memoization is an optimization technique that caches a function's results based on input value.
    </p>
    <p>
        Given an initially unique input the result is calculated and cached,
        such that any subsequent calls with the same input return the initial cached result
        (instead of performing a recalculation).
    </p>
    <p>
        Memoization is a <i>time-space tradeoff</i>
        (i.e. subsequent computation time is saved at the cost of keeping initial calculated results in memory)
    </p>
    <p>
        Memoization is useful for pure functions (that always return the same result for the same input),
        whose results can be cached without a concern that they may be out of date.
    </p>
    <p>
        Python 3.2+ provides an simple memoization solution in the form of the
        <a href="https://docs.python.org/3/library/functools.html#functools.lru_cache" target="_blank">
            lru_cache
        </a>
        decorator.
    </p>
    <p>
        For example, a memoized solution for computing the Fibonacci sequence simply requires the addition of the @lru_cache decorator.
    </p>
<pre><code>@lru_cache()
def fib(n):
    if n < 2:
        return n
    return fib(n-2) + fib(n-1)</code>
</pre>

    <footer id="article-footer">
        <p>
            <b>P.S.</b>
        </p>
        <p>
            For more details on memoization:
        </p>
        <ul>
            <li>
                <a href="https://mike.place/2016/memoization/" target="_blank">
                    Memoization in Python
                </a>
                by Mike Lee Williams.
            </li>
            <li>
                <a href="https://habrahabr.ru/post/335866/" target="_blank">
                    Мемоизация и каррирование (Python)
                </a>
                by German Gorelkin.
            </li>
        </ul>
        <p>
            For more details on Python's lru_cache decorator:
        </p>
        <ul>
            <li>
                <a href="https://docs.python.org/3/library/functools.html#functools.lru_cache" target="_blank">
                    lru_cache
                </a>
                section of Python documentation.
            </li>
        </ul>
    </footer>

{% endblock %}

app/templates/articles/20170820-singleton-pattern.html
{% extends "blog_article.html" %}

{% block article_title %}Singleton Pattern{% endblock %}

{% block article_body %}
https://dzone.com/articles/what-the-singleton-pattern-costs-you
{% endblock %}

app/templates/articles/20170820-solid-principles.html
{% extends "blog_article.html" %}

{% block article_title %}SOLID principles for better object-oriented design{% endblock %}

{% block article_body %}
{% endblock %}

app/templates/articles/20170822-peer-review.html
{% extends "blog_article.html" %}

{% block article_title %}Peer Review{% endblock %}

{% block article_body %}
    https://www.ibm.com/developerworks/rational/library/11-proven-practices-for-peer-review/
    https://dev.to/lpasqualis/making-babies-emotions-and-code-reviews
{% endblock %}

app/templates/articles/20170828-python-asyncio.html
{% extends "blog_article.html" %}

{% block article_title %}Python's Asyncio{% endblock %}

{% block article_body %}
    - asyncio enables single-threaded concurrency
        - as opposed to (a conceptually more intuitive) multi-threaded concurrency
    - single-threaded concurrency is achieved using an event loop
        - event loop is also how javascript works???
    - event loop works with callback functions that are given to it, and it executes them in some order
        - it is essentially an infinite "while true" loop that executes whatever callback functions are given to it???
{% endblock %}

app/templates/articles/20170831-emotional-intelligence.html
{% extends "blog_article.html" %}

{% block article_title %}Emotional Intelligence{% endblock %}

{% block article_body %}
    <header id="article-header">
        <p>
            This article is my thoughts and summary on
            <a href="http://www.bakadesuyo.com/2017/08/emotionally-intelligent/" target="_blank">
                New Neuroscience Reveals 3 Secrets That Will Make You Emotionally Intelligent
            </a>
            by Eric Barker.
        </p>
    </header>

    - understanding emotions and what they are...
        - "Emotions aren’t hardwired or universal. They’re concepts that we learn. And so they can differ from culture to culture."
        - "Utka Eskimos have no concept of “Anger.” The Tahitians have no concept of “Sadness.” This last item is very difficult for Westerners to accept… life without sadness? Really? When Tahitians are in a situation that a Westerner would describe as sad, they feel ill, troubled, fatigued, or unenthusiastic, all of which are covered by their broader term pe’ape’a."
        - "If you had been raised somewhere different, you might feel something different. Emotions vary between people ... And they vary dramatically between cultures."
            - "But if you only have concepts for “anger”, “happiness”, and “sadness” then that’s all you’re ever going to see."
            - Often we pick these concepts up just from living in a culture, others we’re taught explicitly as children. And they’re transmitted from one person to the next, from one generation to the next.
            - When we experience a sensation, an emotion concept is triggered like a memory and actually constructed by the brain. It’s nearly immediate and you’re largely unaware of the process.
            - "If your doctor came back with a diagnosis of “you’re sick”, you’d sue the quack for malpractice. Doctors need to be able to distinguish between “chancre” and “cancer.” And you need to know the difference between “sad” and “lonely.”"
    - Eric's 3 steps to developing a better emotional intelligence:
        - Improve emotional granularity
            - "Having lower emotional granularity is associated with a lot of bad things — like emotional and personality disorders.""
            - learn to have a more granular understanding of emotions
            - "when you’re able to finely discern what you’re feeling, you’re able to do something constructive to deal with the problems causing them."
                - "If the only negative emotion concept you have is “me feel bad” you’re going to have a difficult time making yourself feel better. So you’ll resort to ineffective coping methods like, oh, bourbon."
                - "But if you’re able to distinguish the more specific “I feel alone” from merely “me feel bad” you’re able to deal with the problem: you call a friend."
        - Improve emotional dictionary
            - "Learning more emotion words is the key to recognizing more subtle emotion concepts."
            - "So are you angry, furious, or just cranky? Recognize your emotions. Make the feelings distinct."
            - "learn new emotion words so you can feel new emotions and increase your emotional granularity."
        - Create your own words to better describe your emotions
            - If dictionary words are not enough to describe an emotion, give it your own name to give it granularity and avoid it being bunch with a more general concept.
            - "Those are unique sensations. Give them an emotion. Learn to distinguish them from the other forms of dread or elation."
            - "it might feel a little silly at first but don’t let that hold you back. In Japan they have “age-otori” — “The feeling of looking worse after a haircut.” We’ve all felt that. It just took one emotionally intelligent genius to give it a name."
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {# The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags #}
    <meta name="description" content="Roman Vorobyov is a Full-Stack Web Developer (with a Back-End focus).">
    <meta name="author" content="Roman Vorobyov">
    <meta name="google-site-verification" content="4me7F3vkawQDYk8A2_hdNZuXRDxgQeYJuX7nONjsQZ0">

    <title>{{ title }} | Roman Vorobyov</title>

    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

    {% include 'includes/google_analytics.html' %}
</head>
<body id="{% block body_id %}{% endblock %}">
<div id="page-container" class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <header id="page-header">
                <div class="header-top clearfix">
                    <div class="row-wrapper">
                        <img class="img-rounded" src="{{ url_for('static', filename='avatar.jpg') }}" />
                        <div class="header-title">
                            <div class="header-name">
                                Roman<br />Vorobyov
                            </div>
                            <div class="header-description">
                                Full-Stack<br />Web Developer
                            </div>
                        </div>
                    </div>
                </div>
                <div class="header-bottom">
                    <nav role="navigation">
                        <ul class="nav nav-stacked">
                            <li class="{% if is_nav_blog_active %}active{% endif %}">
                                <a href="{{ url_for('controllers.blog_index') }}">Blog</a>
                            </li>
                            <li class="{% if is_nav_about_active %}active{% endif %}">
                                <a href="{{ url_for('controllers.about') }}">About</a>
                            </li>
                            <li>
                                <a href="{{ url_for('static', filename='RomanVorobyovResume.pdf') }}" target="_blank">Resume</a>
                            </li>
                            <li class="{% if is_nav_contact_active %}active{% endif %}">
                                <a href="{{ url_for('controllers.contact') }}">Contact</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </header>
        </div>
        <div class="col-sm-8">
            <article id="page-content">
                <h1>{{ title }}</h1>
                {% block content %}
                    {{ body | safe }}
                {% endblock %}
            </article>
        </div>
    </div>
</div>
</body>
</html>

app/templates/blog_index.html
{% extends "base.html" %}

{% set is_nav_blog_active = True %}

{% set title = 'Blog' %}

{% block body_id %}page-id-blog-index{% endblock %}

{% block content %}
    <p><i>My thoughts and knowledge base related to software development and other topics.</i></p>
    {% if not articles %}
        No articles found.
    {% else %}
        <ul class="list-unstyled">
            {% for article in articles %}
                <li><a href="{{ article.url }}">{{ article.title }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

app/templates/contact.html
{% extends "base.html" %}

{% set is_nav_contact_active = True %}

{% set title = 'Contact' %}

{% block content %}
    <p>Hey, I'd love to hear from you.</p>
    <p>You can find me here:</p>
    <ul>
        <li><a href="https://linkedin.com/in/romanvorobyov" target="_blank">LinkedIn</a></li>
        <li><a href="https://github.com/ravoro" target="_blank">GitHub</a></li>
    </ul>
{% endblock %}

app/templates/error.html
{% extends "base.html" %}

{% set title = 'Sorry, an error occured...' %}

{% block content %}
    <em><strong>{{ code }}</strong>: {{ description }}</em>
{% endblock %}

app/templates/includes/google_analytics.html
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41765277-1', 'auto');
    ga('send', 'pageview');

</script>